### ISSUE TITLE
[Warning] [gourmand] Two recipes with the same code name of glueportion-pitch-hot were found.

### ISSUE THREAD

**Issue by WickedSchnitzel** [bluelightning32/vs-gourmand#5] opened 2024-12-05 12:01 UTC
see title

**Comment by bluelightning32** [comment] 2024-12-06 04:04
Which mods did you have installed? Which Gourmand version? Was this client side or server side?

Or alternatively, can you upload the log that has all that information?

**Comment by WickedSchnitzel** [comment] 2024-12-08 15:22
8.12.2024 13:50:40 [Warning] [gourmand] Two recipes with the same code name of glueportion-pitch-hot were found. Maybe you copied files within the game's asset folder? All recipe codes:
scrambledeggs
porridge
sulfate-full-chromite
glueportion-pitch-hot
glueportion-pitch-cold
candle
chromium tanned large hide
chromium tanned huge hide
meatystew
vegetablestew
leather-sturdy-plain
leather-sturdy-plain
soup
potash
acid-full-sulfuric
jam
glueportion-pitch-hot
All recipe files:
game:recipes/cooking/scrambledeggs.json
game:recipes/cooking/porridge.json
game:recipes/cooking/sulfate.json
game:recipes/cooking/glue.json
game:recipes/cooking/glue-reheat.json
game:recipes/cooking/candle.json
game:recipes/cooking/hide-chromium.json
game:recipes/cooking/meatystew.json
game:recipes/cooking/vegetablestew.json
game:recipes/cooking/leather.json
game:recipes/cooking/soup.json
game:recipes/cooking/potash.json
game:recipes/cooking/acid.json
game:recipes/cooking/jam.json
em:recipes/cooking/pitch_glue.json

**Comment by WickedSchnitzel** [comment] 2024-12-08 15:24
![Desktop Screenshot 2024 12 08 - 16 22 45 69](https://github.com/user-attachments/assets/be8087aa-b660-4e27-b254-b3f26f2edc20)
![Desktop Screenshot 2024 12 08 - 16 22 53 83](https://github.com/user-attachments/assets/5843a356-b49e-4c49-87f9-15bf04aa1b1f)

**Comment by bluelightning32** [comment] 2024-12-09 04:28
Thanks for providing the logs. This looks like a duplicate of issue#1, for which I've been asking for logs for two months.

I'll attach the fix to that bug.

**Closed by bluelightning32** 2024-12-09 04:28 UTC
